<?php
    $lang['number']   = 'Reference';
    $lang['date']     = 'Fakturerings dato';
    $lang['time']     = 'Fakturerings tid';
    $lang['due']      = 'Forfaldsdato';
    $lang['to']       = 'Fakturering til';
    $lang['from']     = 'Fakturering fra';
    $lang['product']  = 'Vare';
    $lang['qty']      = 'Antal';
    $lang['price']    = 'Pris';
    $lang['discount'] = 'Rabat';
    $lang['vat']      = 'Moms';
    $lang['total']    = 'Total';
    $lang['page']     = 'Side';
    $lang['page_of']  = 'af';
